# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TDP Website Publish
on:
  push:
    branches: [ master ]
jobs:
  www:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    # By default, GH pages support jekyll
    # and ignore underscore paths such as `_next`
    - run: touch out/.nojekyll
    # - run: echo 'www.trunkdataplatform.io' > out/CNAME
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to, default value.
        folder: out # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
